#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World" > /etc/nginx/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.nginx-debian.html;
    location /redirect_me {
        return 301 https://github.com/Ulrich-HOUNGBO;
    }
}" > /etc/nginx/sites-available/default
service nginx restart