#!/usr/bin/env bash
# configure a load-balancing server
	

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.\*
	

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 121976-web-01 18.206.206.136
	server 121976-web-02 54.86.30.114" >> /etc/haproxy/haproxy.cfg
